# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import core_format_pb2 as core__format__pb2


class FormatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.check_format = channel.unary_unary(
                '/Format/check_format',
                request_serializer=core__format__pb2.Request.SerializeToString,
                response_deserializer=core__format__pb2.Response.FromString,
                )


class FormatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def check_format(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FormatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'check_format': grpc.unary_unary_rpc_method_handler(
                    servicer.check_format,
                    request_deserializer=core__format__pb2.Request.FromString,
                    response_serializer=core__format__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Format', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Format(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def check_format(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Format/check_format',
            core__format__pb2.Request.SerializeToString,
            core__format__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
